### ISSUE TITLE
1.12.1: Signal does not hit the block

### ISSUE THREAD

**Issue by Knito58** [Ordinastie/MalisisSwitches#4]
MC 1.12.1, Forge 14.22.0.2463, Malisis Switches 1.12-5.0.0, Gamemode SSP

I used this mod in earlier MC versions and everything was just fine. Now it seems I'm stuck. When holding the power linker the powerlines show up in red and green (when powered) but the consumer does not seem to receive the signal. I'm derping around since two days and cannot get lit up even a simple redstone lamp.

**Comment by Ordinastie** [comment]
Is the log saying anything ?

**Comment by Knito58** [comment]
No sir. The log is very happy about successfully loading the mod. No exception found.

**Comment by Knito58** [comment]
Will look deeper in the logs this evening. Going to work now.

**Comment by Ordinastie** [comment]
Well, without any output pointing towards a potential problem, I don't know.
Only thing left would be compatibility issues with some other mod.
Check if it works with only MalisisSwitches installed.

**Comment by WorseWaif** [comment]
I'm also having this issue with 1.11.2 but later I can try checking it with just the mod as well...

**Comment by Knito58** [comment]
I found something in the fml-junk-earlystartp.log. As this log is *very* big I only put the part with the exceptions to the dropbox.

https://www.dropbox.com/s/dbyh9yfsr2a3xl8/malisis-switches-log.txt?dl=1

**Comment by Knito58** [comment]
When only malisis core and malisis switches is in the mods folder, then it works. Everything is fine in a creative world. Its a good feeling when I link something together and it just works. But where are my mods?

There they are:

 
=============== 
== Mods      == 
=============== 
[1.12]UncraftingTable-1.8-beta5.jar
ActuallyAdditions-1.12.1-r119.jar
advInv-1.12.1-1.4.2.jar
AoV-1.12.1-0.5.1.jar
Aroma1997Core-1.12.1-1.3.0.0.b122.jar
Aroma1997s-Dimensional-World-1.12.1-2.0.0.0.b56.jar
AromaBackup-1.12.1-2.1.1.0.b79.jar
AutoRegLib-1.3-13.jar
backpacks 1.12.1 - 3.3.2.jar
Baubles-1.12-1.5.1.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
Bookshelf-1.12.1-2.1.431.jar
chiselsandbits-14.6.jar
Controlling-3.0.2.jar
crosshairmod-v0.8.2-forge-mc1.12.jar
cucumber[1.12]-1.0.0.jar
cxlibrary-1.12.1-1.6.1.jar
CyclopsCore-1.12-0.10.17.jar
DarkUtils-1.12.1-1.7.169.jar
davincisvessels-1.12-5.335-full.jar
deepresonance-1.12-1.4.9.jar
dooglamoocitiesmod-1.12-1.6.3.jar
ElecCore-1.12-1.8.430.jar
ElevatorMod-1.12-1.3.4.jar
EverlastingAbilities-1.12-1.3.2.jar
extrautils2-1.12-1.6.1.jar
GravelMiner_1.12.1-6.1.2.jar
gravestone-1.8.4.jar
hopperducts-mc1.12-1.5.jar
inventorypets-1.12-1.4.9.8.jar
InventoryTweaks-1.63+beta.108.jar
jei_1.12.1-4.7.8.92.jar
jeiintegration_1.12.1-1.4.2.31.jar
journeymap-1.12.1-5.5.0b3.jar
JustEnoughResources-1.12.1-0.8.4.25.jar
LaserLevel-1.12.1-2.1.0.18-universal.jar
LLOverlayReloaded-1.1.4-mc1.12.jar
lostcities-1.12-1.0.0.jar
LunatriusCore-1.12.1-1.2.0.41-universal.jar
malisiscore-1.12-6.0.4.jar
malisisdoors-1.12-7.0.4.jar
malisisswitches-1.12-5.0.0.jar
mcjtylib-1.12-2.4.4.jar
MCMultiPart-2.2.2.jar
MegaQuarry-1.3-1.12.jar
MobGrindingUtils-0.3.2.jar
ModernLights-1.0.3_1.12.jar
MoreFurnaces-1.12-1.10.1.jar
Morph-o-Tool-1.2-16.jar
movingworld-1.12-5.341-full.jar
mysticalagradditions[1.12]-1.2.2.jar
mysticalagriculture[1.12]-1.6.3.jar
Neat 1.4-15.jar
NoMoreRecipeConflict-0.9(1.12).jar
notenoughwands-1.12-1.5.9.jar
OptiFine_1.12.1_HD_U_C5.jar
OverpoweredInventory-1.12-2.3.1.jar
platforms-1.12.0-1.4.0.1.jar
ProjectE-1.12-PE1.1.0.jar
RandomThings-MC1.12.1-4.0.5.jar
refinedstorage-1.5.17.jar
rftools-1.12-6.13.jar
rftoolsctrl-1.12-1.6.8.jar
rftoolsdim-1.12-5.04.jar
Ruins-1.12.jar
Scannable-MC1.12-1.6.1.12.jar
shetiphiancore-1.12.0-3.5.1.jar
simpleteleporters-1.12-2.1.5.jar
SuperMiner-2.5.33.325.jar
TamModized-1.12.1-0.14.1.jar
thebomplugin-1.12-0.2.3.jar
theoneprobe-1.12-1.4.18.jar
thutcore-5.11.0.jar
thuttech-6.0.4.jar
topaddons-1.12-0.15.0.jar
TrashSlot_1.12.1-8.4.4.jar
VTweaks-1.12-1.4.11.4.jar
Waystones_1.12.1-4.0.15.jar
Wither Skeleton Tweaks-1.12-2.2.3.jar
WTS-1.1.0.jar
xnet-1.12-1.4.0.jar

**Comment by Knito58** [comment]
When I added some new mods, mysticalagradditions crashed the game on startup. I renamed the jar to txt and now it works. Problem gone.

**Comment by xkobalx** [comment]
When using the wand on a switch the an error appears in the console but for some reason doesn't get logged. I was unable to copy text out of the console so here is a screen shot.

![image](https://user-images.githubusercontent.com/10780881/31188197-5f571632-a8f1-11e7-9f26-bbbca9ad4b37.png)

Here is the same for when you right click on the block to link to. 

![image](https://user-images.githubusercontent.com/10780881/31188312-bb5dd254-a8f1-11e7-9d51-fe97f6bbb874.png)

Note this does show the connecting line and highlights the selected block. The signal does not get sent to the targeted block when the switch is pressed. The switch linked or not will power adjacent items similar to a button.

MC 1.12.2 Seems like the same issue reported for 1.12.1 so didn't create a new issue.  Images above are from a test performed on a server. Running Forge 14.23.0.2495. 

Also, confirmed not working on single player.

**Comment by D3nnis3n** [comment]
I can confirm the links do not work on SMP or SSP in 1.12.2 - redstone will just not be transfered even though link is established and nvisible.

This is what it Spams to me in console when creating links:
https://gist.github.com/D3nnis3n/3d1ed18edf3fe7480a2787841385596c

**Comment by Knito58** [comment]
I thought i had solved the problem by dooming an offending mod. But meanwhile the problem is back. The switches do not transmit the signal anymore. Cannot tell which mod it was this time - I update all my mods and Forge with new releases every day.

**Comment by Darkmega18** [comment]
confirmed. I've been annoyed by having this occur also. I've had to use icky vanilla redstone to power stuff up. D: links visibly connect, but don't actually send any redstone signals in 1.12.2. these switches were kinda the whole reason I downloaded this at first, and then all your other bits too, ordinastie, so please fix update them if you can. :V but I read above that having only core and switches could be a potential go to have it work. so I might try that when I get to it.
