### ISSUE TITLE
ETA?

### ISSUE THREAD

**Issue by Kowantify** [Ordinastie/MalisisSwitches#7]
Do you have a possible ETA of the malisis switches fix? im very excited and so are my pals on the server we love this mod!

**Comment by Ordinastie** [comment]
As soon as I am able to build.
(Note : you didn't have to reopen an issue, you can still comment on closed ones.)

**Comment by Kowantify** [comment]
Ah sorry about that, would it be done before next week? Or is it gonna be a hot while?

**Comment by Ordinastie** [comment]
Hopefully within a few days.
